
version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET_STAGE}
    ports:
      - ${PORT_OUTPUT}:3000
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .db.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data